export const ROOMS = [
    {
        roomId: 1,
        name: 'Bathroom 1',
        x: 100,
        y: 125,
        width: 300,
        height: 200,
        devices: [
            {
                deviceId: 1,
                name: 'Fan',
                x: 50,
                y: 50,
            },
            {
                deviceId: 2,
                name: 'Overhead Light',
                x: 250,
                y: 150,
            },
            {
                deviceId: 3,
                name: 'Window',
                x: 0,
                y: 120,
            },
        ],
    },
    {
        roomId: 2,
        name: 'Bedroom 1',
        x: 400,
        y: 75,
        width: 275,
        height: 275,
        devices: [
            {
                deviceId: 1,
                name: 'Lamp 1',
                x: 50,
                y: 50,
            },
            {
                deviceId: 2,
                name: 'Lamp 2',
                x: 225,
                y: 50,
            },
            {
                deviceId: 3,
                name: 'Overhead Light',
                x: 50,
                y: 225,
            },
            {
                deviceId: 4,
                name: 'TV',
                x: 225,
                y: 225,
            },
            {
                deviceId: 5,
                name: 'Window 1',
                x: 140,
                y: 0,
            },
            {
                deviceId: 6,
                name: 'Window 2',
                x: 275,
                y: 140,
            },
        ],
    },
    {
        roomId: 3,
        name: 'Living Room',
        x: 400,
        y: 350,
        width: 750,
        height: 325,
        devices: [
            {
                deviceId: 1,
                name: 'TV',
                x: 450,
                y: 50,
            },
            {
                deviceId: 2,
                name: 'Lamp 1',
                x: 360,
                y: 50,
            },
            {
                deviceId: 3,
                name: 'Lamp 2',
                x: 540,
                y: 50,
            },
            {
                deviceId: 4,
                name: 'Overhead Light',
                x: 375,
                y: 275,
            },
            {
                deviceId: 5,
                name: 'HVAC',
                x: 700,
                y: 275,
            },
            {
                deviceId: 6,
                name: 'Window 1',
                x: 750,
                y: 135,
            },
            {
                deviceId: 7,
                name: 'Window 2',
                x: 750,
                y: 200,
            },
            {
                deviceId: 8,
                name: 'Window 3',
                x: 0,
                y: 115,
            },
            {
                deviceId: 9,
                name: 'Front Door',
                x: 0,
                y: 50,
            },
            {
                deviceId: 10,
                name: 'Back Door',
                x: 650,
                y: 0,
            },
        ],
    },
    {
        roomId: 4,
        name: 'Garage',
        x: 100,
        y: 525,
        width: 300,
        height: 300,
        devices: [
            {
                deviceId: 1,
                name: 'Washer',
                x: 250,
                y: 50,
            },
            {
                deviceId: 2,
                name: 'Dryer',
                x: 250,
                y: 250,
            },
            {
                deviceId: 3,
                name: 'Garage Door',
                x: 300,
                y: 100,
            },
            {
                deviceId: 4,
                name: 'Garage Door 1',
                x: 0,
                y: 125,
            },
            {
                deviceId: 5,
                name: 'Garage Door 2',
                x: 0,
                y: 200,
            },
        ],
    },
    {
        roomId: 5,
        name: 'Kitchen',
        x: 500,
        y: 675,
        width: 500,
        height: 300,
        devices: [
            {
                deviceId: 1,
                name: 'Overhead Light',
                x: 250,
                y: 50,
            },
            {
                deviceId: 2,
                name: 'Washer',
                x: 50,
                y: 150,
            },
            {
                deviceId: 3,
                name: 'Fridge',
                x: 450,
                y: 150,
            },
            {
                deviceId: 4,
                name: 'Stove',
                x: 160,
                y: 250,
            },
            {
                deviceId: 5,
                name: 'Oven',
                x: 250,
                y: 250,
            },
            {
                deviceId: 6,
                name: 'Microwave',
                x: 340,
                y: 250,
            },
            {
                deviceId: 7,
                name: 'Window 1',
                x: 50,
                y: 300,
            },
            {
                deviceId: 8,
                name: 'Window 2',
                x: 450,
                y: 300,
            },
        ],
    },
    {
        roomId: 6,
        name: 'Bedroom 2',
        x: 1150,
        y: 150,
        width: 275,
        height: 275,
        devices: [
            {
                deviceId: 1,
                name: 'Lamp 1',
                x: 50,
                y: 50,
            },
            {
                deviceId: 2,
                name: 'Lamp 2',
                x: 225,
                y: 50,
            },
            {
                deviceId: 3,
                name: 'Overhead Light',
                x: 135,
                y: 225,
            },
            {
                deviceId: 4,
                name: 'Window 1',
                x: 105,
                y: 0,
            },
            {
                deviceId: 5,
                name: 'Window 2',
                x: 170,
                y: 0,
            },
        ],
    },
    {
        roomId: 7,
        name: 'Bathroom 2',
        x: 1425,
        y: 190,
        width: 300,
        height: 200,
        devices: [
            {
                deviceId: 1,
                name: 'Fan',
                x: 250,
                y: 50,
            },
            {
                deviceId: 2,
                name: 'Overhead Light',
                x: 50,
                y: 150,
            },
            {
                deviceId: 3,
                name: 'Window',
                x: 300,
                y: 120,
            },
        ],
    },
    {
        roomId: 8,
        name: 'Bedroom 3',
        x: 1150,
        y: 600,
        width: 275,
        height: 275,
        devices: [
            {
                deviceId: 1,
                name: 'Lamp 1',
                x: 50,
                y: 50,
            },
            {
                deviceId: 2,
                name: 'Lamp 2',
                x: 225,
                y: 50,
            },
            {
                deviceId: 3,
                name: 'Overhead Light',
                x: 140,
                y: 225,
            },
            {
                deviceId: 4,
                name: 'Window 1',
                x: 275,
                y: 150,
            },
            {
                deviceId: 5,
                name: 'Window 2',
                x: 75,
                y: 275,
            },
        ],
    },
];

export const ELECTRICITY_USAGE_DATA = [
    { month: 'January', wattage: 500 },
    { month: 'February', wattage: 650 },
    { month: 'March', wattage: 800 },
    { month: 'April', wattage: 725 },
    { month: 'May', wattage: 675 },
    { month: 'June', wattage: 450 },
    { month: 'July', wattage: 500 },
    { month: 'August', wattage: 750 },
    { month: 'September', wattage: 800 },
    { month: 'October', wattage: 775 },
    { month: 'November', wattage: 825 },
    { month: 'December', wattage: 950 },
];

export const WATER_USAGE_DATA = [
    { month: 'January', volume: 250 },
    { month: 'February', volume: 235 },
    { month: 'March', volume: 189 },
    { month: 'April', volume: 290 },
    { month: 'May', volume: 315 },
    { month: 'June', volume: 310 },
    { month: 'July', volume: 265 },
    { month: 'August', volume: 240 },
    { month: 'September', volume: 190 },
    { month: 'October', volume: 150 },
    { month: 'November', volume: 230 },
    { month: 'December', volume: 280 },
];
